/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-container-highest": "#d8dedc",
              "primary": "#006948",
              "outline": "#747876",
              "on-surface": "#2b2f2e",
              "secondary-dim": "#46524d",
              "inverse-on-surface": "#9a9e9c",
              "primary-container": "#6effc1",
              "secondary-container": "#d9e5df",
              "on-tertiary-fixed-variant": "#005361",
              "surface-container-low": "#eef2ef",
              "on-secondary-fixed": "#36423d",
              "error-dim": "#9f0519",
              "on-secondary-fixed-variant": "#525e59",
              "on-error-container": "#570008",
              "on-tertiary-fixed": "#00333d",
              "tertiary-fixed-dim": "#00cded",
              "surface-tint": "#006948",
              "on-error": "#ffefee",
              "surface-variant": "#d8dedc",
              "tertiary-fixed": "#00dcfe",
              "surface-container-high": "#dfe4e1",
              "surface-container": "#e5e9e7",
              "tertiary-container": "#00dcfe",
              "surface": "#f4f7f5",
              "inverse-surface": "#0b0f0e",
              "inverse-primary": "#6effc1",
              "outline-variant": "#aaaeac",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#e9f6ef",
              "on-background": "#2b2f2e",
              "on-tertiary": "#ddf7ff",
              "secondary": "#525e59",
              "surface-dim": "#d0d6d3",
              "primary-dim": "#005b3e",
              "tertiary": "#006575",
              "on-surface-variant": "#585c5b",
              "tertiary-dim": "#005866",
              "on-primary-fixed": "#004b32",
              "on-primary-fixed-variant": "#006b4a",
              "background": "#f4f7f5",
              "primary-fixed": "#6effc1",
              "on-primary-container": "#006041",
              "surface-bright": "#f4f7f5",
              "error": "#b31b25",
              "on-tertiary-container": "#004955",
              "error-container": "#fb5151",
              "on-primary": "#c8ffe1",
              "primary-fixed-dim": "#5df0b4",
              "secondary-fixed": "#d9e5df",
              "secondary-fixed-dim": "#cad7d1",
              "on-secondary-container": "#48544f"
          },
          fontFamily: {
              "headline": ["'Plus Jakarta Sans'", "sans-serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
          },
          borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
      },
  },
  plugins: [],
}